### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by targos** [comment]
I'll investigate. I had the same error on my machine but thought it was because I'm on Windows :D

**Comment by targos** [comment]
I added `FORCE_COLOR: 0` to the environment of the child process.

**Comment by richardlau** [comment]
Maybe we can [enable dependabot](https://github.com/nodejs/admin/issues/430) here?

**Comment by Trott** [comment]
> Maybe we can [enable dependabot](https://github.com/nodejs/admin/issues/430) here?

Yes, done.

**Pull request merged**
