### PR TITLE
warn for 50 < title <= 72

### PR DESCRIPTION
**Pull request by refack**
if https://github.com/nodejs/node/pull/16523 lands

### CODE REVIEW

**Comment by joyeecheung** [comment]
CI is not working because this repo has been moved, but this does not pass the tests locally. Can you fix the lint errors and the test? Thanks! @refack

**Comment by refack** [comment]
BTW: Just checked travis, it is working, it just can't update it's status: https://travis-ci.org/nodejs/core-validate-commit/builds/300959458

Tests are WIP

**Comment by joyeecheung** [comment]
@refack Yes, I think I need to add this repo to https://github.com/nodejs/github-bot/pull/156

**Comment by refack** [comment]
https://travis-ci.org/nodejs/core-validate-commit/jobs/301331767 ✔️

**Comment by joyeecheung** [comment]
Ping @evanlucas this looks ready to land, I've bumped into the 72 chars limit quite a bit lately when landing commits

**Comment by joyeecheung** [comment]
@evanlucas Thanks, I've taken the liberty to merge this. Can you release a new version?

**Comment by evanlucas** [comment]
Published in v3.5.0. Thanks! Also, @joyeecheung do you need publish access to this package? If so, I can add you :]

**Comment by evanlucas** [comment]
@joyeecheung what is your npm username?

**Comment by joyeecheung** [comment]
@evanlucas Same as my github handle: https://www.npmjs.com/~joyeecheung

**Comment by evanlucas** [comment]
Done. Thanks!

**Pull request merged**
