### PR TITLE
rules: check spaces in commit title

### PR DESCRIPTION
**Pull request by targos**
- Do not allow consecutive spaces
- Require a space after the subsystems

### CODE REVIEW

**Comment by targos** [comment]
Can I merge this? Who is responsible for the module?

**Comment by Trott** [comment]
> Can I merge this? Who is responsible for the module?

@targos Since you're a member of @nodejs/automation-collaborators, you are 👍 to merge this. (You can see the teams listed under Settings -> Collaborators & teams.)

Someone will still need to tag and publish a new version of the package for this to take effect. Package maintainers according to https://www.npmjs.com/package/core-validate-commit are Evan, Joyee, and "Node.js Foundation". Not sure who has publishing rights via that last account, but if you know, please tell me!

**Comment by richardlau** [comment]
> "Node.js Foundation". Not sure who has publishing rights via that last account, but if you know, please tell me!

That's an account managed by the Build WG:
https://github.com/nodejs/build/blob/master/doc/access.md#npm-management
> * The [`nodejs-foundation`](https://www.npmjs.com/~nodejs-foundation) npm user, which is managed by the Build WG, is an administrator on all Foundation npm packages. It is the means to add or remove other module collaborators, and shouldn't be used to publish releases.

**Comment by joyeecheung** [comment]
> Can I merge this? Who is responsible for the module?

I guess with the current state it's probably..me? But I would be very happy to see more people getting access to this repo and the npm module since I am also a bit overloaded and don't always see the notifications here...

Judging by the recent activity I think we can add @targos @Trott and @richardlau to the npm collaborators team, if they are willing to be added.

(@richardlau would you be interested in getting write access to this repo? Either as a collaborator of this repo, or just as a member of @nodejs/automation-collaborators , I guess for the latter we can open an issue to https://github.com/nodejs/automation first)

cc @evanlucas (not sure if you are still on leave, sorry for the noise)

**Comment by targos** [comment]
I would be happy to have access to npm publication rights

**Comment by joyeecheung** [comment]
I have added @targos and @richardlau as npm collaborators and added @richardlau as a collaborator in this repo (@targos should have access through TSC / automation-collaborators already)

**Comment by targos** [comment]
Do we have a special process to publish packages on npm?
Or is it just `npm version whatever && npm publish`?

**Comment by joyeecheung** [comment]
@targos That's what I do, yes, I guess you can also updates the release notes on GitHub but I don't know who actually reads those..

**Pull request merged**
