### PR TITLE
rules: add `watch` subsystem

### PR DESCRIPTION
**Pull request by MoLow**

### CODE REVIEW

**Comment by MoLow** [comment]
@nodejs/tsc who can approve this?

**Review by aduh95 — APPROVED** [review]

**Comment by Trott** [comment]
I guess this most impacts @nodejs/releasers?

**Comment by Trott** [comment]
Not sure how I feel about the underbar. The only place that appears otherwise is in subsystem strings that correspond to modules that have an underbar in their name. Any reason this isn't just `watch`? For that matter, might it just be fine using `cli` or something like that? Does it need a new subsystem?

Non-blocking questions for discussion. If other people think it's fine or if this has already been discussed and I just missed it, feel free to land without engaging on this. :-D

**Comment by MoLow** [comment]
the underbar is not very important - we can change to `watch`.
there are a couple of PR's related to watch mode that I dont think fit the `cli` subsystem:
https://github.com/nodejs/node/pull/45259
https://github.com/nodejs/node/pull/45271

**Review by RafaelGSS — COMMENTED** [review]
I'm +1 for `watch`

**Comment by Trott** [comment]
Sorry to be a pain about this, but can you squash and rewrite the commit message? I want to make sure that if we add the `commit-queue` label to this, the commit message says `watch` and not `watch_mode`.

**Review by Trott — APPROVED** [review]

**Comment by Trott** [comment]
We'll have to be careful to make sure that people don't use this for the fs watcher function, but I think that's a pretty unlikely error for someone to make and that reviewers would catch the error, so I'm 👍 on this.

**Comment by MoLow** [comment]
@Trott done. can this be merged?

**Review by RafaelGSS — APPROVED** [review]

**Review by GeoffreyBooth — APPROVED** [review]

**Comment by Trott** [comment]
> @Trott done. can this be merged?

Whoops, forgot that we use the commit button in this repo so I guess I could have done it right in the interface. Anyway, yes, merged, thanks!

**Pull request merged**
