### PR TITLE
remove 50 char limit on title line per new project guidelines

### PR DESCRIPTION
**Pull request by Trott**

### CODE REVIEW

**Comment by joyeecheung** [comment]
Right...there is https://github.com/nodejs/core-validate-commit/pull/22

**Comment by Trott** [comment]
> IIUC we are not removing the limit, just relaxing it to 72chars? 

@joyeecheung I had assumed the test for 72 characters that applies to other lines would apply to the title line, but now I see that is incorrect. I'll try to modify it to flag the title line too...

**Comment by Trott** [comment]
> Right...there is #22

@joyeecheung Did that end up in the wrong window? Was that meant to refer another issue/PR to this one?

**Comment by Trott** [comment]
Oh, it looks like #18 might be a better solution?

**Comment by Trott** [comment]
I'm going to close this in favor of #18 but feel free to ping or re-open if you think this might be better.

**Comment by joyeecheung** [comment]
@Trott Yes I meant #18...copy-pasting gone wrong 😓

**Pull request closed without merging**
